/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.9.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as actionItems from "../actionItems.js";
import type * as analytics from "../analytics.js";
import type * as crons from "../crons.js";
import type * as dailyMetrics from "../dailyMetrics.js";
import type * as generateActionItems from "../generateActionItems.js";
import type * as getUpdatedCalendar from "../getUpdatedCalendar.js";
import type * as http from "../http.js";
import type * as sleepScores from "../sleepScores.js";
import type * as stressScores from "../stressScores.js";
import type * as stresses from "../stresses.js";
import type * as zodSchema from "../zodSchema.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  actionItems: typeof actionItems;
  analytics: typeof analytics;
  crons: typeof crons;
  dailyMetrics: typeof dailyMetrics;
  generateActionItems: typeof generateActionItems;
  getUpdatedCalendar: typeof getUpdatedCalendar;
  http: typeof http;
  sleepScores: typeof sleepScores;
  stressScores: typeof stressScores;
  stresses: typeof stresses;
  zodSchema: typeof zodSchema;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
